<?php require_once 'templates/layout/header.phtml'; ?>

<div class='error-pag'>
    <h1>Ups! Hubo un error</h1>
    <img src='images/haaland.jpg' alt='error-haal' id='imagen-error'>
    <h4>Parece que la pagina que estas buscando no existe o no se pudo encontrar</h4>
    <button id='btn-inicio'><a href='home' id='btn-a-home'>Inicio</a></button>
</div>

<?php require_once 'templates/layout/footer.phtml'; ?>