<?php require_once "templates/layout/header.phtml" ?>

<div class="div-not-loged">
    <h2>No estás logueado!</h2>
    <p>Esta función está disponible solamente para usuarios logueados y verificados</p>
    <img src="images/notloged.jpg" alt="notloged" id="notloged">
    <button id='btn-inicio'><a href='home' id='btn-a-home'>Inicio</a></button>
</div>


<?php require_once "templates/layout/footer.phtml"; ?>