<?php require_once "templates/layout/header.phtml"; ?>

<div class="d-flex align-items-center mt-2">
    <div class="col-md-2 img-fluid"><img src="<?php echo $dataTeam->logo ?>" /></div>
    <div class="col-md-4">
        <h2><?php echo $dataTeam->nombre ?></h2>
    </div>

</div>


<div class="playersInTeam">
    <h2 class="lead">Jugadores de este equipo</h2>
    <?php foreach ($players as $teams): ?>
        <li class="list-group-item list-group-item-light"><?php echo "$teams->nombre" ?></li>
    <?php endforeach ?>

</div>

<?php require_once "templates/layout/footer.phtml"; ?>