</main>
<footer>
    <div class="footer-content">
        <div class="footer-separation">
            <div class="redes">

                <ul>
                    <h4>Nuestras Redes</h4>
                    <li class='li-footer'>Instagram</li>
                    <li class='li-footer'>X</li>
                    <li class='li-footer'>Youtube</li>
                    <li class='li-footer'>Facebook</li>
                </ul>
            </div>

            <div class="info">
                <ul>
                    <h4>Info importante</h4>
                    <li class='li-footer'>Preguntas Frecuentes</li>
                    <li class='li-footer'>Contacto</li>
                    <li class='li-footer'>Derechos</li>
                    <li class='li-footer'>Licencias®</li>
                </ul>
            </div>

        </div>
        <p id='footer-copyright'>&copy;Tudai/Todos los derechos reservados/2024</p>

    </div>


</footer>
</body>