<!DOCTYPE html>
<html lang="es">

<?php require_once "router.php"; ?>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PremStats</title>
    <base href="<?= BASE_URL ?>">
    <link rel="stylesheet" href="<?= BASE_URL ?>css/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>

<body>

    <header>
        <div class="header-principal">

            <img src="images/premstats.png" alt="logo" id="logo">

            <div class="titulos">
                <h1>PremStats</h1>
                <h2>Lo mejor del futbol ingles</h2>
            </div>

        </div>

        <div class="sign">
            <ul>
                <li><a href="showSignin" id="sign-in">Log in</a></li>

                <li><a href="signout" id="sign-up">Log out</a></li>

            </ul>
        </div>



    </header>